In [1]:
#1
import math
num=int(input("Enter a number:"))
flag=0

for i in range (2,math.ceil(num/2)+1):
    if num%i==0:
        flag=1
        break

if num==1:
    print("Neither Prime nor Composite")
elif flag==0:
    print("Prime")
else:
    print("Composite")
    

Enter a number:2
Prime


In [ ]:
#2
limit=int(input("Enter a limit: "))
l=[]
for i in range (0,limit):
    l.append(input())

print(l)

item=input("Enter the item: ")
for i in l:
    if item in l:
        l.remove(item)


print(l)

In [ ]:
#3
str=input("Enter a string:")
str=str.lower()
l=str.split(" ")
l2=[]
l3=[]
count=0
for i in l:
    if i not in l3:
        l3.append(i)
        l2.append([i,l.count(i)])
        
print(l2)

In [6]:
#4
r = int(input("Enter the rows:"))
c = int(input("Enter the columns:"))
m1=[]
for i in range(r):
    m1.append([])
    for j in range(c):
           m1[i].append(int(input()))
print(m1)
m2=[]
for i in range(r):
    m2.append([])
    for j in range(c):
           m2[i].append(int(input()))
print(m2)
m3=[]
for i in range(r):
    m3.append([])
    for j in range(c):
        m3[i].append(m1[i][j]+m2[i][j])
print("sum:")
print(m3)

p=0
m4=[[0 for j in range(c)]for i in range(r)]

for i in range(len(m1)): 
    for j in range(len(m2[0])):
        for k in range(len(m2)):
            m4[i][j]+=m1[i][k]*m2[k][j]
print()            
print("Product:")
for i in m4:

    print(i)

Enter the rows:2
Enter the columns:2
1
0
0
1
[[1, 0], [0, 1]]
2
3
4
5
[[2, 3], [4, 5]]
sum:
[[3, 3], [4, 6]]

Product:
[2, 3]
[4, 5]


In [19]:





#NUMPY Programs







In [7]:
#5
import numpy as np
arr=np.arange(1,16)
size=arr.size
print("Original array")
print(arr)
new=int(input("Enter the new value for the 8th element"))
arr[7]=new
rev=np.flip(arr)
arr1=np.delete(arr,(len(arr)-1))
mat=arr1.reshape(7,2)
print("Size:")
print(size)
print("Repleaced array:")
print(arr)
print("Reversed:")
print(rev)
print("Matrix:")
print(mat)


Original array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Enter the new value for the 8th element7
Size:
15
Repleaced array:
[ 1  2  3  4  5  6  7  7  9 10 11 12 13 14 15]
Reversed:
[15 14 13 12 11 10  9  7  7  6  5  4  3  2  1]
Matrix:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  7]
 [ 9 10]
 [11 12]
 [13 14]]


In [8]:
#6
import numpy as np
arr2=np.arange(22,42)
arr2.resize(5,4)
print("Array is: \n",arr2)
print("Shape is: ",arr2.shape)
print("Its type: ",arr2.dtype)
print("Datatype: ",type(arr2))

Array is: 
 [[22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]
Shape is:  (5, 4)
Its type:  int64
Datatype:  <class 'numpy.ndarray'>


In [9]:
#7
arr=np.zeros((8,8),dtype='int')
arr[::2,::4]=1
arr[::2,1::4]=1
arr[1::2,3::4]=1
arr[1::2,2::4]=1
print(arr)

[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]


In [10]:
#8
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,5,8,9])
print("Array1: ",arr1)
print("Array2: ",arr2)
print("Check Array1 elements in Array2: ")
print(np.in1d(arr1,arr2))

Array1:  [1 2 3 4 5]
Array2:  [3 5 8 9]
Check Array1 elements in Array2: 
[False False  True False  True]


In [11]:
#9
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
print("Array1: ",arr1)
print("Array2: ",arr2)
print("Intersection: ",np.intersect1d(arr1,arr2))
print("Union: ",np.union1d(arr1,arr2))

Array1:  [1 2 3 4 5]
Array2:  [4 5 6 7 8]
Intersection:  [4 5]
Union:  [1 2 3 4 5 6 7 8]


In [10]:
#10.1
import numpy as np
a=np.array([2,3,4,7],dtype=np.int32)
np.savetxt("/home/student/Documents/DSML ABIN/file1.txt",a,fmt="%5d",delimiter=",")
x=np.loadtxt(open("/home/student/Documents/DSML ABIN/file1.txt","rb"),delimiter=",")
print("textfile",x)
x=np.loadtxt(open("/home/student/Documents/DSML ABIN/test2.csv","rb"),delimiter=",")
print("csv file",x)

textfile [2. 3. 4. 7.]
csv file [2. 3. 4. 7.]


In [11]:
#10.2
m=np.arange(1,5).reshape(2,2)
print("Numpy array:",m,sep="\n")
print("Converted list: ",m.tolist(),sep="\n")

Numpy array:
[[1 2]
 [3 4]]
Converted list: 
[[1, 2], [3, 4]]


In [13]:
#10.3
r,c=int(input("Enter the number of rows: ")),int(input("Enter the number of columns: "))
print("Enter the array row wise")
a=list(map(int,input().split()))
a=np.array(a).reshape(r,c)
print("Numpy Array: ",a,sep="\n")
for i in range(c):
    print("Column: ",i+1,":",a[:,i])

Enter the number of rows: 3
Enter the number of columns: 3
Enter the array row wise
1 9 2 8  3 7 4 6 5
Numpy Array: 
[[1 9 2]
 [8 3 7]
 [4 6 5]]
Column:  1 : [1 8 4]
Column:  2 : [9 3 6]
Column:  3 : [2 7 5]


In [16]:
#10.4
m1=np.arange(1,5).reshape(2,2)
m2=np.arange(5,9).reshape(2,2)
print("matrix1: ",m1,sep="\n")
print("matrix2: ",m2,sep="\n")
print("Product: ",np.matmul(m1,m2),sep="\n")
              #or np.dot(m1,m2)
print("Sum is: ",m1 + m2,sep="\n")    

matrix1: 
[[1 2]
 [3 4]]
matrix2: 
[[5 6]
 [7 8]]
Product: 
[[19 22]
 [43 50]]
Sum is: 
[[ 6  8]
 [10 12]]


In [17]:
#10.5
a=np.arange(9).reshape(3,3)
eigval,eigvec=np.linalg.eig(a)
print("Eigen values: ",eigval,"Eigen vector: ",eigvec,sep="\n")

Eigen values: 
[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]
Eigen vector: 
[[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [18]:
#10.6
a=np.arange(1,5).reshape(2,2)
print("Diagonal matrix: ",a,sep="\n")
print("Transpose of this matrix: ",np.transpose(a),sep="\n")
print("Determinant of this matrix: ",np.linalg.det(a),sep="\n")
try:
    print("Inverse of this matrix: ",np.linalg.inv(a),sep="\n")
except:
    print("No inverse as it is a singular notebook")

Diagonal matrix: 
[[1 2]
 [3 4]]
Transpose of this matrix: 
[[1 3]
 [2 4]]
Determinant of this matrix: 
-2.0000000000000004
Inverse of this matrix: 
[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:






#PANDAS PROGRAMS








In [2]:
import pandas as pd

In [3]:
ds=pd.Series([2,4,6,8,10])
print(ds)


0     2
1     4
2     6
3     8
4    10
dtype: int64


In [5]:
#1. Write a Pandas program to create and display a one-dimensional array like object containing an array of data
 
import pandas as pd
print(" Write a Pandas program to create and display a one-dimensional array like object")
s=pd.Series([2,4,5,6,10]) 
print(s) 

 Write a Pandas program to create and display a one-dimensional array like object
0     2
1     4
2     5
3     6
4    10
dtype: int64


In [6]:
#2. Write a Pandas program to add, subtract, multiply and divide two Pandas Series

import pandas as pd
print("Write a Pandas program to add, subtract, multiply and divide two Pandas Series")
ds1=pd.Series ([2,4,5,6,10]) 
ds2=pd.Series([9,4,1,6,1]) 
ds=ds1+ds2 
print("Add two series :") 
print(ds) 
print("substract two series") 
ds=ds1 -ds2 
print(ds) 
print("multply two series") 
ds=ds1 * ds2 
print(ds) 
print("divide two series") 
ds=ds1 / ds2 
print(ds) 


Write a Pandas program to add, subtract, multiply and divide two Pandas Series
Add two series :
0    11
1     8
2     6
3    12
4    11
dtype: int64
substract two series
0   -7
1    0
2    4
3    0
4    9
dtype: int64
multply two series
0    18
1    16
2     5
3    36
4    10
dtype: int64
divide two series
0     0.222222
1     1.000000
2     5.000000
3     1.000000
4    10.000000
dtype: float64


In [7]:
# 3.  1)Write a Pandas program to create and display a DataFrame ‘Examdata’ from a specified dictionary 
#       data(7 records) which has the fields 1)name 2)Score 3)Attempts 4)Qualify

import numpy as np 
import pandas as pd 
exam_data={  
'name': ['anu', 'manu', 'sam', 'abc', "nithu","nivya", "rinu"], 
'score' : [7,8,9,7, np.nan,4,11], 
'attempts': [1,3,2,6,2,4,1], 
'qualify': ['yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes'] 
    }
df=pd.DataFrame(exam_data) 
print(df) 
print("A ********************************************* A")


#     3.2)save it as a csv file and retrieve it.

print("csv file") 
df.to_csv("f.csv", index=True) 
df2=pd.read_csv("f.csv") 
print(df2) 
print("B ********************************************* B")


#     3.3)Select 'name' and 'score' columns in rows 1, 2,4, 6

print(df.iloc[[1, 2, 4, 6], [0, 1]])
print("C ********************************************* C")

#     3.4)select the rows where the number of attempts in the examination is greater than 2

print(df[df['attempts']>2]) 
print("D ********************************************* D")


#     3.5)count the number of rows and columns of the DataFrame

print(df.count()) 
rows = df.shape[0] 
cols = df.shape[1] 
print("number of rows", rows) 
print("number of colums", cols) 
print( "E ********************************************* E") 

#     3.6)select rows where Number of attempts in the examination is less than 4 and score greater than 10

print("attempts in the examination is less than 4 :\n ",df[df['attempts']<4])

print( " Number of attempts in the examination is less than 4 and score greater than 10: \n" ,df[(df['attempts'] < 4) & (df['score'] >10)])
print("F ********************************************* F")


#     3.7)select rows where score are missing

print(df [df['score'].isnull()]) 
print("G ********************************************* G")

#     3.8)change the score in row 3 to 12

print("\nOriginal data frame:") 
print(df.loc[3],[0,1]) 
print("\nChange the score in row 3 to 12:") 
df.loc[3, 'score'] = 12 
print(df.loc[3],[0,1]) 
print("H ********************************************* h")


#     3.9)delete the last row ,append a new row and return the original data frame

df.loc[8] = ['karthika', 9,1, 'yes'] 
print("Print all records after insert a new record: ") 
print(df) 
print("\nDelete the new row and display the original rows:") 
df = df.drop(8) 
print(df) 
print("I ********************************************* I")


#     3.10)replace the 'qualify' column contain the values 'yes' and 'no' with True and False.

df['qualify'] = df['qualify'].map({'yes': True, 'no': False}) 
print(df) 
print(df) 
print("J ********************************************* J") 


#     3.11)insert a new column ‘color’ and populate it.

print("Original rows:") 
print(df) 
color = ['Red', 'Blue', 'Orange', 'Red', 'white', 'White', 'Blue'] 
df['color'] = color 
print("\nNew DataFrame after inserting the 'color' column") 
print(df)
print("K ********************************************* K")

    name  score  attempts qualify
0    anu    7.0         1     yes
1   manu    8.0         3     yes
2    sam    9.0         2     yes
3    abc    7.0         6     yes
4  nithu    NaN         2      no
5  nivya    4.0         4     yes
6   rinu   11.0         1     yes
A ********************************************* A
csv file
   Unnamed: 0   name  score  attempts qualify
0           0    anu    7.0         1     yes
1           1   manu    8.0         3     yes
2           2    sam    9.0         2     yes
3           3    abc    7.0         6     yes
4           4  nithu    NaN         2      no
5           5  nivya    4.0         4     yes
6           6   rinu   11.0         1     yes
B ********************************************* B
    name  score
1   manu    8.0
2    sam    9.0
4  nithu    NaN
6   rinu   11.0
C ********************************************* C
    name  score  attempts qualify
1   manu    8.0         3     yes
3    abc    7.0         6     yes
5  nivya    4.0    

In [8]:
# 4.Write a pandas program to create a dataframe(6 records) which has the fields id,name,age,degree,cgpa

import numpy as np
import pandas as pd
student={
    "id":[100,101,102,103,104,105],
    "name":["anu","savitha","malavika","amala","sam","karthik"],
    "age":[20,23,18,19,np.nan,34],
    "degree":["BCA","BA","B.TEC",np.nan,"BSC","B.COM"],
    "cgpa":[7.00,8,4,9,np.nan,np.nan]
}

df1=pd.DataFrame(student)
print( " dataframe with 6 records \n\n ",df1)

#   4.1)insert a new column ‘class’ into the dataframe and populate values

df1.insert(2, "class", [1, 3, 2, 4,7,8], True)
print(" \n insert a new column class ","\n *************************\n",df1)
print("A ********************************************* A")

#   4.2)Find out total no.of columns in the dataframe

print("Total no.of columns in the dataframe : ",len(df1.columns))
print("B ********************************************* B")

#   4.3)select top 3 rows ,last 4 rows

print("top 3 rows  : \n",df1.head(3))
print("\n last 4 rows :  \n ",df1.tail(3))
print("C ********************************************* C")

#   4.4)delete all rows which have null values

print("Before removing : \n" ,df1)
print("                                       \n")
df3=df1.dropna()
print("After removing:\n",df3)
print("D ********************************************* D")

#   4.5)drop ‘id’ column

newdf = df1.drop("id", axis='columns')

print(df1)
print("              ")
print( "Remove id : \n ",newdf)
print("                                 ")
print("E ********************************************* E")

#   4.6)select name,cgpa from 2 to 5 records

print(df1.loc[[2,3,4,5],["name","cgpa"]])
print("F ********************************************* F")

#   4.7)fill null values in the age column with mean value

print("Before filling null value \n ",df1)
meanVal = df1['age'].mean()
print("                   ")
print("MEAN VALUE",meanVal)
df1['age'].fillna(value=meanVal,inplace=True)
print("             ")
print(df1)
print("G ********************************************* G")


 dataframe with 6 records 

      id      name   age degree  cgpa
0  100       anu  20.0    BCA   7.0
1  101   savitha  23.0     BA   8.0
2  102  malavika  18.0  B.TEC   4.0
3  103     amala  19.0    NaN   9.0
4  104       sam   NaN    BSC   NaN
5  105   karthik  34.0  B.COM   NaN
 
 insert a new column class  
 *************************
     id      name  class   age degree  cgpa
0  100       anu      1  20.0    BCA   7.0
1  101   savitha      3  23.0     BA   8.0
2  102  malavika      2  18.0  B.TEC   4.0
3  103     amala      4  19.0    NaN   9.0
4  104       sam      7   NaN    BSC   NaN
5  105   karthik      8  34.0  B.COM   NaN
A ********************************************* A
Total no.of columns in the dataframe :  6
B ********************************************* B
top 3 rows  : 
     id      name  class   age degree  cgpa
0  100       anu      1  20.0    BCA   7.0
1  101   savitha      3  23.0     BA   8.0
2  102  malavika      2  18.0  B.TEC   4.0

 last 4 rows :  
      id  

In [28]:
# 5)a)Load iris dataset into a dataframe
df=pd.read_csv("/home/student/Documents/DSML ABIN/Sample Files/iris.csv")
print(df,"\n")
print(" ********************************************* ")
#   b)Take its descriptive statistics
df.describe()
print(" ********************************************* ")
#   c)delete all rows which have null values
df.dropna(inplace=True)
print(df,"\n")
print(" ********************************************* ")
#   d)select the Species classes,Count the no.of datas in each class
spcount=df['species'].value_counts()
print(spcount)
print(" ********************************************* ")
#   e)Map the species classes into 1,2 and 3
df['species']=df['species'].map({'setosa':1, 'versicolor':2,'virginica':3})
print(df['species'])
print(df)
print("*********************************************")
#   f)Print the standard deviation and mean of petal length
std=df['petal_length'].std()
mean=df['petal_length'].mean()
print("Standard deviation of petal length",std)
print("Mean of petal length:",mean)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns] 

 ********************************************* 
 ********************************************* 
     sepal_length  sepal_width  petal_length  peta

In [29]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.054000      3.758667     1.198667    2.000000
std        0.828066     0.433594      1.764420     0.763161    0.819232
min        4.300000     2.000000      1.000000     0.100000    1.000000
25%        5.100000     2.800000      1.600000     0.300000    1.000000
50%        5.800000     3.000000      4.350000     1.300000    2.000000
75%        6.400000     3.300000      5.100000     1.800000    3.000000
max        7.900000     4.400000      6.900000     2.500000    3.000000